In [1]:
import clean_df
import pandas as pd
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

C:\Users\LT-MSI\.conda\envs\ADD\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
data = clean_df.clean()

In [3]:
data.describe()

,Peak CCU,Required age,Price,Discount,DLC count,Reviews,Metacritic score,User score,Positive,Score rank,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,has_header image,has_screenshots,has_website,has_support url,has_support email,has_about the game,Ratio positive vote
count,1.131210e+05,113121.000000,113121.000000,113121.000000,113121.000000,113121.000000,113121.000000,113121.000000,1.131210e+05,40.000000,...,113121.000000,1.131210e+05,113121.000000,113121.000000,113121.000000,113121.000000,113121.000000,113121.000000,113121.000000,82037.000000
mean,5.886970e+01,0.174318,5.041820,19.738545,0.554415,0.265972,2.730925,0.026609,1.107718e+03,99.175000,...,14.797314,1.806474e+02,15.811812,0.999505,0.999470,0.432669,0.471363,0.879085,0.998471,0.758784
std,3.882519e+03,1.684912,12.760783,29.477639,14.361501,0.911446,14.071254,1.452215,2.917317e+04,0.675107,...,281.081865,1.163711e+04,306.237297,0.022244,0.023025,0.495448,0.499181,0.326030,0.039077,0.238371
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,98.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000e+00,0.000000,0.890000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,99.000000,...,0.000000,0.000000e+00,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.650000
50%,0.000000e+00,0.000000,2.740000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000e+00,99.000000,...,0.000000,0.000000e+00,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.818792
75%,0.000000e+00,0.000000,5.990000,50.000000,0.000000,0.000000,0.000000,0.000000,4.400000e+01,100.000000,...,0.000000,0.000000e+00,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.944444
max,1.013936e+06,21.000000,999.980000,100.000000,3703.000000,14.000000,97.000000,100.000000,7.642084e+06,100.000000,...,20088.000000,3.429544e+06,20088.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [4]:
data.head()

,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,Supported languages,Full audio languages,...,Categories,Genres,Tags,has_header image,has_screenshots,has_website,has_support url,has_support email,has_about the game,Ratio positive vote
AppID,,,,,,,,,,,,,,,,,,,,,
730,Counter-Strike 2,"Aug 21, 2012",100000000 - 200000000,1013936,0,0.00,0,1,"[Czech, Danish, Dutch, English, Finnish, Frenc...","[English, Indonesian]",...,"[Multi-player, Cross-Platform Multiplayer, Ste...","[Action, Free To Play]","[FPS, Shooter, Multiplayer, Competitive, Actio...",1,1,1,0,0,1,0.866932
570,Dota 2,"Jul 9, 2013",100000000 - 200000000,623941,0,0.00,0,2,"[Bulgarian, Czech, Danish, Dutch, English, Fin...","[English, Korean, Simplified Chinese, Vietnamese]",...,"[Multi-player, Co-op, Steam Trading Cards, Ste...","[Action, Strategy, Free To Play]","[Free to Play, MOBA, Multiplayer, Strategy, e-...",1,1,1,0,0,1,0.815193
578080,PUBG: BATTLEGROUNDS,"Dec 21, 2017",100000000 - 200000000,314682,13,0.00,0,0,"[English, Korean, Simplified Chinese, French, ...",[],...,"[Multi-player, PvP, Online PvP, Stats, Remote ...","[Action, Adventure, Massively Multiplayer, Fre...","[Survival, Shooter, Battle Royale, Multiplayer...",1,1,1,1,0,1,0.594406
3419430,Bongo Cat,"Mar 5, 2025",0 - 20000,164168,0,0.00,0,0,"[English, German, Dutch, Japanese, Korean, Pol...",[],...,"[Single-player, Multi-player, Co-op, Online Co...","[Casual, Indie, Massively Multiplayer, Simulat...",[],1,1,0,0,1,1,NaN
2622380,ELDEN RING NIGHTREIGN,"May 29, 2025",2000000 - 5000000,163599,17,29.99,25,1,"[English, Japanese, French, Italian, German, S...","[English, Traditional Chinese]",...,"[Single-player, Multi-player, Co-op, Online Co...","[Action, RPG]","[Souls-like, Online Co-Op, Rogue-like, Multipl...",1,1,0,1,0,1,0.744625

In [5]:
list_cols = ["Genres", "Tags", "Supported languages", "Publishers", "Developers", "Full audio languages", "Categories"]
cols = [c for c in data.columns if c not in list_cols]
n_duplicated = data[cols].duplicated().sum()
print(f"Number of duplicated rows: {n_duplicated}\n")

df = pd.DataFrame({
    'n_unique':data[cols].nunique(),
    'n_missing':data[cols].isna().sum(),
    'missing_ratio':data[cols].isna().mean(),
    'dtype':data[cols].dtypes.values
})

display(
    df.style.background_gradient(cmap='BuPu')
        .format({"missing_ratio": "{:.2%}"})
)

Number of duplicated rows: 0

In [11]:
# Run python clean_df.py in terminal to create clean.csv

data2 = pd.read_csv("clean.csv", index_col=False) 
data2 = data2.set_index("AppID")

In [12]:
list_cols = ["Genres", "Tags", "Supported languages", "Publishers", "Developers", "Full audio languages", "Categories"]
cols = [c for c in data2.columns if c not in list_cols]
n_duplicated = data2[cols].duplicated().sum()
print(f"Number of duplicated rows: {n_duplicated}\n")

df = pd.DataFrame({
    'n_unique':data2[cols].nunique(),
    'n_missing':data2[cols].isna().sum(),
    'missing_ratio':data2[cols].isna().mean(),
    'dtype':data2[cols].dtypes.values
})

display(
    df.style.background_gradient(cmap='BuPu')
        .format({"missing_ratio": "{:.2%}"})
)

Number of duplicated rows: 0