In [26]:
library(tidyverse)
library(janitor)     
library(skimr)       
library(kableExtra)

In [27]:
#Data Loading

In [32]:
data <- read_csv("games.csv")

# afficher un aperçu en coupant le texte trop long
library(stringr)                     # si ce n'est pas déjà chargé

data %>%
  mutate(`About the game` = str_trunc(`About the game`, 20, ellipsis = "...")) %>%
  head()

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 122611 Columns: 39
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (19): Name, Release date, Estimated owners, About the game, Supported la...
dbl (16): AppID, Peak CCU, Required age, Price, Discount, DLC count, Metacri...
lgl  (4): Windows, Mac, Linux, Score rank

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  AppID   Name                                  Release date Estimated owners
1 2539430 Black Dragon Mage Playtest            Aug 1, 2023  0 - 0
2  496350 Supipara - Chapter 1 Spring Has Come! Jul 29, 2016 0 - 20000
3 1034400 Mystery Solitaire The Black Raven     May 6, 2019  0 - 20000
4 3292190 버튜버 파라노이아 - Vtuber Paranoia   Oct 31, 2024 0 - 20000
5 3631080 Maze Quest VR                         Apr 24, 2025 0 - 20000
6 1654170 Agony VR                              Apr 5, 2023  0 - 20000
  Peak CCU Required age Price Discount DLC count About the game       ⋯
1 0        0             0.00  0       0         NA                   ⋯
2 0        0             5.24 65       0         Springtime, April... ⋯
3 0        0             4.99  0       0         Immerse yourself ... ⋯
4 1        0             8.99  0       1         synopsis 'Hello, ... ⋯
5 0        0             4.99  0       0         Its not just a Ma... ⋯
6 0        0            13.99  0       0         A JOURNEY THROUGH... ⋯
  Average playtime forever Average playtime two weeks Median playtime forever
1 0                        0                          0
2 8                        0                          8
3 0                        0                          0
4 0                        0                          0
5 0                        0                          0
6 0                        0                          0
  Median playtime two weeks Developers           Publishers
1 0                         NA                   NA
2 0                         minori               MangaGamer
3 0                         Somer Games          8floor
4 0                         유진게임즈           유진게임즈
5 0                         Reality Expanded LLC Reality Expanded LLC
6 0                         Ignibit              Ignibit,Madmind Studio
  Categories
1 NA
2 Single-player,Steam Trading Cards,Steam Cloud,Family Sharing
3 Single-player,Family Sharing
4 Single-player,Steam Achievements,Family Sharing
5 Single-player,VR Only,Steam Leaderboards,Family Sharing
6 Single-player,Tracked Controller Support,VR Only,Family Sharing
  Genres
1 NA
2 Adventure
3 Casual
4 Casual,Indie,Simulation
5 Action,Early Access
6 Action,Adventure
  Tags
1 NA
2 Adventure,Visual Novel,Anime,Cute
3 Casual,Card Game,Solitaire,Puzzle,Hidden Object,2D,Colorful,Stylized,Logic,Mystery,Atmospheric,Family Friendly,PvE,Tutorial,Singleplayer,Tabletop
4 NA
5 NA
6 NA
  Screenshots
1 https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2539430/ss_7d9504b958d0b143d053d31cb74b375daba338d6.1920x1080.jpg?t=1699268702,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2539430/ss_85d2749d23e115b4d44e8ed1024c55a6be524fde.1920x1080.jpg?t=1699268702,"
2 https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_0a5ff85870a1c2221e495b75a5c7b9e248eb3249.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_f53e18a6c7be8eeb39e7c8efff8395b444786f68.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_1f86a8d171a549c504acd6592f559fc4bd9bd448.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_f40b6e8e535047b60412b8f102b907cb2317d53d.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_32c2149186b260804a2a8bed8e595f36228f8e16.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_abc2fe50c29b2621ae970f846a1e11d2e66c7394.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_020efba82647ba7aeb72185ab0becfc53c68238f.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_3fa4c80d58d7c156d30a0098ed57a236257afc9c.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_96b7faa121b03555c6a31877fbcdac961bccdadc.1920x1080.jpg?t=1725519097,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/ss_d0bfd6e4501bf94d7cd7727d2f1d085a86d68adb.1920x1080.jpg?t=1725519097,"
3 https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1034400/ss_12d8bb27a16046fe548818dcd0f5d7d0e2038179.1920x1080.jpg?t=1687434115,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1034400/ss_e809678d186bc47558dba4f421b2535e28b6bb7b.1920x1080.jpg?t=1687434115,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1034400/ss_87ccbb03192630d7876e315eea690691e906e232.1920x1080.jpg?t=1687434115,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1034400/ss_36846149295dcf5e7da3f0297ed03e0d2425f619.1920x1080.jpg?t=1687434115,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1034400/ss_9c5838d0d7db31ce10f63042a1af032507d59129.1920x1080.jpg?t=1687434115,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1034400/ss_ed7360a46cd443f713dcaa3203165d7354466f5b.1920x1080.jpg?t=1687434115,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1034400/ss_14e08c4ea0076001a9170e0911f4d79e39b1663b.1920x1080.jpg?t=1687434115,"
4 https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3292190/ss_87f071dbf846e7832ff49d68b0d7a8b6509bcda6.1920x1080.jpg?t=1742217574,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3292190/ss_b06de7c2dc64df5f902afd99d4597160e4cafa74.1920x1080.jpg?t=1742217574,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3292190/ss_62ccffe85aba180968351f956a29ddd3755142dd.1920x1080.jpg?t=1742217574,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3292190/ss_344b2862e0b796d4f8dd35a1adcf26b4a297e100.1920x1080.jpg?t=1742217574,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3292190/ss_403b782eea8df4e49776e76adf036d4f23d29ffc.1920x1080.jpg?t=1742217574,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3292190/ss_9d6d55599bb73b91b649117962071be4314ccb6e.1920x1080.jpg?t=1742217574,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3292190/ss_7bc6f1e34aa3916b0c3a9c1ed81ec35e7d9315d9.1920x1080.jpg?t=1742217574,"
5 https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3631080/3c3874df57f1a1a1f544e81ee21581f8b52140b5/ss_3c3874df57f1a1a1f544e81ee21581f8b52140b5.1920x1080.jpg?t=1746637727,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3631080/91c2337931ff18946abef274e7f50403aaf6867a/ss_91c2337931ff18946abef274e7f50403aaf6867a.1920x1080.jpg?t=1746637727,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3631080/d1c42fd33f3e017dddda432864e4f650488520d8/ss_d1c42fd33f3e017dddda432864e4f650488520d8.1920x1080.jpg?t=1746637727,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3631080/cb0f1a5e54cce8333b89d9540a3a12f98430b54f/ss_cb0f1a5e54cce8333b89d9540a3a12f98430b54f.1920x1080.jpg?t=1746637727,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3631080/5686c1d26e3bd45c1cc00be8964da9609b0b061b/ss_5686c1d26e3bd45c1cc00be8964da9609b0b061b.1920x1080.jpg?t=1746637727,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3631080/0f94522cb4582a7a8c05a9fdf4f72e712baf6a8e/ss_0f94522cb4582a7a8c05a9fdf4f72e712baf6a8e.1920x1080.jpg?t=1746637727,"
6 https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1654170/ss_2e51840454f318d83c3838ec9b4d74fa3b032fa0.1920x1080.jpg?t=1681546360,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1654170/ss_ca0d0c986e65dbb6b2f8ef943c83a72cbf00be1d.1920x1080.jpg?t=1681546360,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1654170/ss_3896dfed29b8fa56376c329f7d08ceba905cc26b.1920x1080.jpg?t=1681546360,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1654170/ss_9b2755e0c0bf5ba91570caa87aedd7a2c957a4cd.1920x1080.jpg?t=1681546360,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1654170/ss_8c0ee93ad3f614017547cd3e74fdd6b4cf80b28c.1920x1080.jpg?t=1681546360,"

In [33]:
#Data Cleaning

In [34]:
# nettoyage des noms de colonnes pour faciliter les références
# (vous aviez chargé janitor plus haut)
data <- data %>% clean_names()

# retirer en amont les jeux incomplets (au moins une valeur manquante)

data <- data %>%
  mutate(
    missing_count = 
      is.na(categories) +
      is.na(genres) 
  ) %>%
  filter(missing_count == 0 ) %>%
  select(-missing_count)

# dédupliquer : si le même name apparaît plusieurs fois, garder la ligne
# qui a le plus grand "peak_ccu" (plus représentatif du nombre de joueurs)
data <- data %>%
  arrange(name, desc(peak_ccu)) %>%
  distinct(name, .keep_all = TRUE)

# reconstruire le résumé après épuration et déduplication
summary_df <- data.frame(
  n_unique = sapply(data, n_distinct),
  n_missing = sapply(data, function(x) sum(is.na(x))),
  missing_ratio = sapply(data, function(x) mean(is.na(x))),
  dtype = sapply(data, class)
)
summary_df %>%
  arrange(desc(missing_ratio))
names(data)

# vérification du nombre de jeux restants
nrow(data)

                           n_unique n_missing missing_ratio dtype
score_rank                      1   112121    1.0000000000  logical
metacritic_url               4141   107952    0.9628169567  character
reviews                     11745   100228    0.8939270966  character
notes                       18429    89930    0.8020798958  character
website                     38927    63498    0.5663345850  character
support_url                 34695    59121    0.5272964030  character
tags                        75906    30388    0.2710286209  character
support_email               59519    13578    0.1211013102  character
publishers                  61639      538    0.0047983875  character
about_the_game             111465      171    0.0015251380  character
developers                  69678      139    0.0012397321  character
header_image               112066       56    0.0004994604  character
app_id                     112121        0    0.0000000000  numeric
name                       112121        0    0.0000000000  character
release_date                 5072        0    0.0000000000  character
estimated_owners               14        0    0.0000000000  character
peak_ccu                     1105        0    0.0000000000  numeric
required_age                   15        0    0.0000000000  numeric
price                         915        0    0.0000000000  numeric
discount                       88        0    0.0000000000  numeric
dlc_count                     116        0    0.0000000000  numeric
supported_languages         18880        0    0.0000000000  character
full_audio_languages         3668        0    0.0000000000  character
windows                         2        0    0.0000000000  logical
mac                             2        0    0.0000000000  logical
linux                           2        0    0.0000000000  logical
metacritic_score               73        0    0.0000000000  numeric
user_score                     31        0    0.0000000000  numeric
positive                     5477        0    0.0000000000  numeric
negative                     2670        0    0.0000000000  numeric
achievements                  447        0    0.0000000000  numeric
recommendations              5252        0    0.0000000000  numeric
average_playtime_forever     2994        0    0.0000000000  numeric
average_playtime_two_weeks    984        0    0.0000000000  numeric
median_playtime_forever      2472        0    0.0000000000  numeric
median_playtime_two_weeks     985        0    0.0000000000  numeric
categories                  13224        0    0.0000000000  character
genres                       2692        0    0.0000000000  character
screenshots                112064        0    0.0000000000  character

 [1] "app_id"                     "name"
 [3] "release_date"               "estimated_owners"
 [5] "peak_ccu"                   "required_age"
 [7] "price"                      "discount"
 [9] "dlc_count"                  "about_the_game"
[11] "supported_languages"        "full_audio_languages"
[13] "reviews"                    "header_image"
[15] "website"                    "support_url"
[17] "support_email"              "windows"
[19] "mac"                        "linux"
[21] "metacritic_score"           "metacritic_url"
[23] "user_score"                 "positive"
[25] "negative"                   "score_rank"
[27] "achievements"               "recommendations"
[29] "notes"                      "average_playtime_forever"
[31] "average_playtime_two_weeks" "median_playtime_forever"
[33] "median_playtime_two_weeks"  "developers"
[35] "publishers"                 "categories"
[37] "genres"                     "tags"
[39] "screenshots"

[1] 112121